name: Deploy to S3

on:
  push:
    branches:
      - master
  env:
    CI: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - name: Use Node.js 16
        uses: actions/checkout@v4

      - name: Build and package
        run: |
          npm run build

      - name: Deploy to S3
        uses: aws-actions/configure-aws-credentials@v4
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: zeeotherbucket
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
